### ISSUE TITLE
Command yum not found?

### ISSUE THREAD

**Issue by TimMurnaghan** [graalvm/container#10]
Trying to use this as a base image and add a postgres client - but I can't figure out where the yum command has gone.

Can't see anything in the Docker file that's removing it - but it's just not there in the running image.

Any clues gratefully received.

**Comment by abdelhaira** [comment]
Since you can't find yum command, i would assume that you're using ol8 based image, they don't have yum or dnf, but they do have microdnf, please try the command:
`microdnf install postgresql`

**Comment by lgdd** [comment]
Hi 👋 I had the same issue with `ghcr.io/graalvm/graalvm-ce:20.3.1.2` (not an ol8 based image) but moving to `microdnf` solved it. Thanks @abdelhaira!

**Comment by abdelhaira** [comment]
That's great, closing this.
