### ISSUE TITLE
Do not override ENTRYPOINT for truffleruby image

### ISSUE THREAD

**Issue by eregon** [graalvm/container#14]
Due to https://github.com/graalvm/container/pull/11#discussion_r617619334

I think this is super confusing, it took me over 5 minutes just to find how to get a shell.
```
$ docker run --rm -it ghcr.io/graalvm/truffleruby:latest bash     
truffleruby: No such file or directory -- bash (LoadError)

$ docker run --rm -it ghcr.io/graalvm/truffleruby:latest /bin/bash             
truffleruby: /bin/bash:1: Invalid char `\177' ('') in expression (SyntaxError)

$ docker run --rm -it --entrypoint bash ghcr.io/graalvm/truffleruby:latest 
bash-4.4#
```

cc @ezzarghili 
I think let's remove the `ENTRYPOINT` and just have `CMD` as `ruby` or `ruby --version`.
In fact we should maybe also drop `CMD` altogether, so then the default is a shell, which is the most useful.

**Comment by eregon** [comment]
See https://github.com/oracle/truffleruby/issues/2349#issuecomment-843128482, probably best to follow the `ruby` image for this.

**Comment by HoneyryderChuck** [comment]
@eregon thanks for starting this issue, I was actually going to mention that as well 🙏

**Comment by eregon** [comment]
@abdelhaira @ezzarghili Could we update existing truffleruby images (and probably graalvm-ce too) to include this fix and https://github.com/graalvm/container/issues/9?

**Comment by abdelhaira** [comment]
@eregon truffleruby and graalvm-ce images have been updated, and both fixes have been merged to the repository

**Comment by eregon** [comment]
Thanks, I confirm it works now :)
