### ISSUE TITLE
Docker Image for GraalVM Java 16

### ISSUE THREAD

**Issue by StefanLobbenmeier** [graalvm/container#17]
The latest GraalVM Release also includes a build for Java 16. Will you also add a container for that?

**Comment by he3als** [comment]
Would be very useful.

**Comment by StefanLobbenmeier** [comment]
As a first attempt I created an image based on the Java 11 Dockerfile but I replaced the 11 with 16, haven’t tested if it works yet:

https://hub.docker.com/r/stefanlobbenmeierricoh/graalvm

**Comment by mzingg** [comment]
would appreciate this as well

**Comment by abdelhaira** [comment]
Unfortunately, we don't create containers for experimental platforms.
Closing this.

**Comment by StefanLobbenmeier** [comment]
@abdelhaira Thanks for clarifying.

In the meantime - is it ok for me to leave that container public as is or do I need to add some more information like Licence or Disclaimer?

**Comment by abdelhaira** [comment]
@StefanLobbenmeier yes, you can leave the container public, but please do add a copy of [UPL](https://www.oracle.com/downloads/licenses/upl-license.html) to your repository
