### ISSUE TITLE
GraalVM CE docker image should support M1 

### ISSUE THREAD

**Issue by FieryCod** [graalvm/container#18]
Currently `ghcr.io/graalvm/graalvm-ce:ol8-java8-21.1.0` outputs a warning that the underlying architecture is not aarch64. Although native-image works it's very slow on M1. I don't yet know how M1 could officially be supported. For now I will leave this issue for further consideration.

**Comment by StefanLobbenmeier** [comment]
Can you run 
docker image inspect ghcr.io/graalvm/graalvm-ce:ol8-java8-21.1.0 | grep Arch

Because from looking at this: https://github.com/graalvm/container/pkgs/container/graalvm-ce/2598796?tag=ol8-java11-21.1.0 it looks like there is an image for arm64 architecture as well

**Comment by ezzarghili** [comment]
There is no support for aarch64 for JDK8, you can use jdk11+ variants, they are all multi arch and support aarch64 too.
