### ISSUE TITLE
Invalid ARM64 Image for graalvm-ce:java11-21.2.0, mixed with X86 binaries

### ISSUE THREAD

**Issue by goafabric** [graalvm/container#20]
The ARm64 Image for graalvm-ce:java11-21.2.0 seems to be invalid and mixed up with X86 Graalvm Binaries.

Executing "gu" inside the Container gives:
"/lib64/ld-linux-x86-64.so.2: No such file or directory"

"file /bin/bash" returns:
ELF 64-bit LSB shared object, ARM aarch64,

While the File Command on the "gu" and java indicates,
that the X86 Version is installed.

The Java8 version however, seems to be build correctly.

**Comment by abdelhaira** [comment]
There was an issue with the CI, this has been fixed now, Thank you @goafabric

**Comment by goafabric** [comment]
Thank you to
for the fast fix
