### ISSUE TITLE
Publish official graalvm-ce Docker images

### ISSUE THREAD

**Issue by cap10morgan** [graalvm/container#21]
I am one of the maintainers of the official clojure Docker images, and I would like to provide variants of those images with graalvm & native-image already baked in as the Clojure community has developed quite a bit of interest in building native-images w/ GraalVM. :)

However, I can't do that unless the graalvm-ce images that I would use in my `FROM` lines are themselves official images on Docker Hub. Would that be something you all were willing to do?

**Comment by ezzarghili** [comment]
Hi, thanks for your interest in GraalVM, please note that the images published here are the official docker images, there are no plans to publish them again on docker hub.

> However, I can't do that unless the graalvm-ce images that I would use in my FROM lines are themselves official images on Docker Hub

Not sure about this this requirement, please talk to whoever set this limitation, and let them know that the GraalVM docker images in github are official images.

You can either use the images from the github registry or https://container-registry.oracle.com both are currently supported as official release vehicles.

Please feel free to reopen if you need assistance on using these.

**Comment by cap10morgan** [comment]
Sorry, I think some clarification is needed. I understand that these are your official images, but they are not Docker Official Images as described here: https://docs.docker.com/docker-hub/official_images/

Docker Hub itself sets the limitation that Official Images can only build from other official images (here: https://github.com/docker-library/official-images#repeatability).

So in order for me to build an official image from yours, it would need to be published as a Docker Official Image on Docker Hub as outlined in those linked documents.

Does that help clarify?

**Comment by cap10morgan** [comment]
I don't have permission to reopen this issue, but I think it should be reopened.
