### ISSUE TITLE
Official Docker Hub image

### ISSUE THREAD

**Issue by cap10morgan** [graalvm/container#22]
In #21 I asked about publishing a Docker Official Image (as described here: https://github.com/docker-library/official-images) but was told you all had no plans to do that.

Is it OK if I (and the rest of the Docker+GraalVM community) do it instead? I have a PR open here to add it, but they want to make sure it's something you all are supportive of first: https://github.com/docker-library/official-images/pull/10936

**Comment by ezzarghili** [comment]
@cap10morgan thank you for the great interest in this, unfortunately we would not be able to support (as in support or being supportive) any images we do not build and we have no plans currently to republish images again to dockerhub repositories.
Our official distribution channel for GraalVM are github registry and container-registry.oracle.com.
