### ISSUE TITLE
Problem with FastR in GraalVM docker container

### ISSUE THREAD

**Issue by long-do** [graalvm/container#23]
Hi,
I have just pulled the Docker image (latest version) of GraalVM, then "gu install R" to install FastR successfully.
In the FastR interpreter (version 4.0.3), I type:
`install.packages("devtools")`
After long time (>1h) of installation I have many errors that I could resolve some of those by install the following libraries in bash:
`microdnf install gcc-gfortran bzip2 libxml2-devel`
I tried again to install the package "devtools", and this time it remained 3 dependents packages impossible to install: "fs" "gert" and "usethis".

The error for "fs" package installation is:
**configure: error: in '/tmp/RtmpkN9qMZ/R.INSTALL1uvvgcvtz68m/fs/src/libuv-1.38.1':
configure: error: cannot run C compiled programs.
If you meant to cross compile, use '--host'.
See 'config.log' for more details
make: *** [Makevars:31: libuv-1.38.1/Makefile] Error 1
ERROR: compilation failed for package ‘fs’
* removing ‘/opt/graalvm-ce-java11-21.2.0/languages/R/library/fs’**

The error for "gert" package installation is:
**Error in polyglot evaluation : /opt/graalvm-ce-java11-21.2.0/languages/R/library/00LOCK-gert/00new/gert
/libs/gert.so: undefined symbol: Rf_warningcall_immediate
ERROR: loading failed
* removing ‘/opt/graalvm-ce-java11-21.2.0/languages/R/library/gert’**

So the packages "usethis" and then "devtools" could not be installed because of not complete dependent packages above.
Please help me to resolve this issue.
Thank you very much.
Best regards

**Comment by abdelhaira** [comment]
Hi, this seems like a FastR related issue, please submit to the [oracle/fastr](https://github.com/oracle/fastr/issues) repository
Closing this
