### ISSUE TITLE
Incorrect Java version for native-image:java11

### ISSUE THREAD

**Issue by Madh93** [graalvm/container#30]
The Java version for the next `native-image` tags does not correspond with the expected version:

- java11
- java11-21
- java11-21.3
- java11-21.3.0
- java11-21.3.0-B1
- ol7-java11
- ol7-java11-21
- ol7-java11-21.3
- ol7-java11-21.3.0
- ol7-java11-21.3.0-b1

Java 11 is expected but Java 17 is used:

    $ docker run -it --rm ghcr.io/graalvm/native-image:java11
    GraalVM 21.3.0 Java 17 CE (Java Version 17.0.1+12-jvmci-21.3-b05)

    $ docker run -it --rm ghcr.io/graalvm/native-image:ol7-java11
    GraalVM 21.3.0 Java 17 CE (Java Version 17.0.1+12-jvmci-21.3-b05)

**Comment by abdelhaira** [comment]
Thank you for reporting this, there was some issue with the ci, deployed images have been fixed now
