### ISSUE TITLE
native-image container not updated with latest release along with graalvm-ce

### ISSUE THREAD

**Issue by brianwyka** [graalvm/container#45]
It seems there is a delay in updating the `native-image` container images for new releases.

For example, `graalvm-ce` has been updated to `22.0.0.2`, but `native-image` is still on `21.3.0`

https://github.com/graalvm/container/pkgs/container/graalvm-ce/versions
https://github.com/graalvm/container/pkgs/container/native-image/versions

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reporting this, it should be fixed now.
