### ISSUE TITLE
graalvm-ce container Does Not Add bin Directory To Path

### ISSUE THREAD

**Issue by brianwyka** [graalvm/container#47]
It would be expected that the `/opt/graalvmce-javaV-XX.Y.Z/bin` be added to the `PATH` environment variable.

I believe this was the case in previous images, but not the case in `22.0.0.2`

**Comment by mlouriz** [comment]
Thanks @brianwyka for reporting this issue. This has been fixed, please feel free to re-open if you are still facing issues.

**Comment by brianwyka** [comment]
Thanks for fixing, and sorry about not getting around with a reproducer.
