### ISSUE TITLE
ol8_graalvm_community.repo returning 404's in graalvm/native-image:latest image

### ISSUE THREAD

**Issue by cap10morgan** [graalvm/container#48]
Steps to reproduce:

1. `docker run --rm -ti --entrypoint bash ghcr.io/graalvm/native-image:latest`
2. (inside container) `microdnf install git` (or any other package)

Observed result:

```
error: cannot update repo 'ol8_graalvm_community': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried; Last error: Status code: 404 for https://yum.oracle.com/repo/OracleLinux/OL8/graalvm/community/repodata/repomd.xml (IP: 69.192.209.79)
```

Expected result: microdnf downloads repo metadata and installs git

**Comment by rodrigar-mx** [comment]
Hi @cap10morgan. Thanks for contributing to graalvm. I have reported this issue internally. An answer will be provided accordingly.

**Comment by ezzarghili** [comment]
Thank you for the report, @mlouriz to take care of fixing this, a workaround would be add to you Dockerfile

```dockerfile
RUN echo -e "\
  [ol8_graalvm_community]\n\
  name=Oracle Linux 8 graalvm community (\$basearch)\n\
  baseurl=https://yum.oracle.com/repo/OracleLinux/OL8/graalvm/community/\$basearch\n\
  gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-oracle\n\
  gpgcheck=1\n\
  enabled=1\
  " > /etc/yum.repos.d/ol8_graalvm_community.repo
```

**Comment by mlouriz** [comment]
Thanks @cap10morgan for reporting this issue. This has been fixed, please feel free to re-open if you are still facing issues.
