### ISSUE TITLE
graalvm/native-image:ol8-java17-22.0.0.2 is missing x86_64-linux-musl-gcc

### ISSUE THREAD

**Issue by axelfontaine** [graalvm/container#50]
This makes it impossible to build fully static images out of the box.

When not using musl, the binaries fail at runtime with

```
dl-call-libc-early-init.c:37: _dl_call_libc_early_init: Assertion `sym != NULL' failed
```

**Comment by mlouriz** [comment]
Hi @axelfontaine, for your information the muslib docker images are now available, you can use them by prefixing tags with muslib, for instance:
docker pull [ghcr.io/graalvm/native-image:muslib-22.3.0](http://ghcr.io/graalvm/native-image:muslib-22.3.0)  for 22.3.0
Please check this [link](https://github.com/graalvm/container/pkgs/container/native-image/versions?filters%5Bversion_type%5D=tagged) for more information.
Please feel free to report if you are facing any issues and thanks for contributing to GraalVM enhancement.
