### ISSUE TITLE
`microdnf: command not found`

### ISSUE THREAD

**Issue by AlexWayfer** [graalvm/container#51]
CI job: https://cirrus-ci.com/task/5553640432730112

Image: `ghcr.io/graalvm/truffleruby:latest`

Everything worked perfectly and became broken, why?

**Comment by mlouriz** [comment]
HI @AlexWayfer, Thank you for the report, the new latest image is based on non ol8 slim image for the full trufflyruby container, the more advanced dnf command is available in this image.
If you want to use the slim runtime image please use the graalvm/truffleruby:slim.

PS: for reproducible builds make sure you use a fixed tag and not latest in your CI jobs.

**Comment by AlexWayfer** [comment]
> HI @AlexWayfer, Thank you for the report, the new latest image is based on non ol8 slim image for the full trufflyruby container, the more advanced dnf command is available in this image.

Thank you. Then the README should be changed, right now I'm seeing info only about `yum` and `microdnf`:

> 1: RPM-based GraalVM Community container images are based on GraalVM components RPMs that are available for Oracle Linux 7 and Oracle Linux 8. Similar to any other available packages, you can install these components using yum on Oracle Linux 7 or microdnf on the Oracle Linux 8 based images.

I ask you to re-open the issue until these changes.

---



> PS: for reproducible builds make sure you use a fixed tag and not latest in your CI jobs.

It's not from Docker Hub, so I don't know how to see a list of versions/tags. Can you help with it please?

**Comment by AlexWayfer** [comment]
@mlouriz I'm ready to create a PR, but I'm really confused. I see no usage of `dnf` on `community/Dockerfile.*`, only `microdnf`. Also there is `OL_BASE` argument with `-slim` default. I don't understand you and I want to use TruffleRuby in CI.

**Comment by LilPoppy** [comment]
> default

Hi @AlexWayfer , I was having the same problem but I hope [this](https://github.com/SpamanDev/StoreChain-Server/blob/main/Dockerfile) will help
