### ISSUE TITLE
truffleruby images are not multi-arch, i.e., no linux-aarch64 images

### ISSUE THREAD

**Issue by eregon** [graalvm/container#55]
https://github.com/graalvm/container/pkgs/container/graalvm-ce/20645535?tag=22.1.0 is multi-arch, but
https://github.com/graalvm/container/pkgs/container/truffleruby/20646687?tag=22.1.0 is not.
Could it be added?
This would be useful, notably to use it in Oracle Cloud, cc @bjfish

**Comment by anicholson-sq** [comment]
I got bit by this today, would be very useful…

**Comment by mlouriz** [comment]
Hi @eregon, @anicholson-sq, please notice that the Truffleruby images are now multi-arch for GraalVM 22.2.0 version. Please feel free to report if you are facing any issues and thanks for contributing to GraalVM enhancement.
