### ISSUE TITLE
Alpine Docker images wanted

### ISSUE THREAD

**Issue by veysiertekin** [graalvm/container#62]
It would be really handy for additional package installations etc

**Comment by oubidar-Abderrahim** [comment]
Hi, thank you for your suggestion, we'll take a look into it and get back to you

**Comment by oubidar-Abderrahim** [comment]
Unfortunately, we have no plans currently for Apline/muslib support for JVM (relies on support from stock JDK), The only thing we provide for Alpine currently is the possibility to build static native image binaries that can be run on it.
