### ISSUE TITLE
VMError$HostedError: java.io.IOException: Cannot run program "/tmp/SVM-/JNIHeaderDirective in ol8-java11-22.3.0

### ISSUE THREAD

**Issue by xlight05** [graalvm/container#66]
**Describe the issue**
$Subject

This is a jar generated from a jvm language called ballerina.It runs just fine with the container `ol8-java11-22.2.0`. But when its bumped to the newest version which is `ol8-java11-22.3.0`, native build shows the following error in the gist. The native build with the same jar and same flags works just fine in my local computer with graalvm 22.3.0. (Ubuntu 20.04). 

https://gist.github.com/xlight05/e7794a603f9dedcd31ecb67533c81852

**Steps to reproduce the issue**
I hacked a sample app for you guys to debug this issue.

```bash
git clone https://github.com/xlight05/graal-container-debug
docker build -t test-graal-debug .
docker run test-graal-debug
```

You can simpy change the `FROM ghcr.io/graalvm/native-image:ol8-java11-22.3.0` to `FROM ghcr.io/graalvm/native-image:ol8-java11-22.2.0` and build again and the native build should work just fine.

Appreciate your help on this issue. Thanks in advance ;)

**Comment by oubidar-Abderrahim** [comment]
Thank you for reporting this, we will take a look into it shortly

**Comment by anuruddhal** [comment]
@oubidar-Abderrahim Were you able to look into this?

**Comment by oubidar-Abderrahim** [comment]
Yes, we're currently investigating to determine the source of this issue.

**Comment by oubidar-Abderrahim** [comment]
Hi @xlight05 @anuruddhal , the issue was caused by a mismatched tag. the tags following this format `<OS>-java<version>-22.3.0` (ex: `ol8-java17-22.3.0`) point to the `muslib` images instead of the normal ones (using `gcc`).

To workaround this, either use a tag like `ol8-java17-22.3.0-b1` (which points to the correct image). Or if you would like to use the static image, add the flags `--static --libc=musl` to the build command/args. you can check [here](https://www.graalvm.org/latest/reference-manual/native-image/guides/build-static-executables/) for more info

**Comment by oubidar-Abderrahim** [comment]
Tag mismatch issue tracked internally on GR 42785

**Comment by xlight05** [comment]
> Hi @xlight05 @anuruddhal , the issue was caused by a mismatched tag. the tags following this format `<OS>-java<version>-22.3.0` (ex: `ol8-java11-22.3.0`) point to the `muslib` images instead of the normal ones (using `gcc`).
> 
> To workaround this, either use a tag like `ol8-java11-22.3.0-b1` (which points to the correct image). Or if you would like to use the static image, add the flags `--static --libc=musl` to the build command/args. you can check [here](https://www.graalvm.org/latest/reference-manual/native-image/guides/build-static-executables/) for more info

Thanks, Currently the idea is to build dynamic images. I think i'll use the tag you pointed.

**Comment by mlouriz** [comment]
This issue is been fixed thanks @xlight05 for reporting, and feel free to reopen if you are facing any issues.
