### ISSUE TITLE
Publish Java19 container images.

### ISSUE THREAD

**Issue by sureshg** [graalvm/container#71]
Right now for GraalVM CE/native-image tyeps, java 19 images are missing and this might be really helpful to test and validate native images using virtual threads.

**Comment by mlouriz** [comment]
Hi @sureshg thanks for reporting this, actually the java 19 is non LTS and we distribute RPMs and container images  for LTS jdk.

**Comment by ezzarghili** [comment]
Actually to be more specific, JDK 19 images were not made available because JDK 19 was set as a experimental in the 23.3 release, we will still public non LTS version as long as they are supported on GraalVM.
