### ISSUE TITLE
[Bug] gu: command not found in ghcr.io/graalvm/jdk:ol8-java17-22.3.0

### ISSUE THREAD

**Issue by KFCFans** [graalvm/container#72]
gu command not found in these images
ghcr.io/graalvm/jdk:ol8-java17-22.3.0
ghcr.io/graalvm/jdk:ol8-java17-22.3.1
***
<img width="974" alt="image" src="https://user-images.githubusercontent.com/9402086/216761437-e03ce141-46a5-425e-9f0b-ccfa4a9c0248.png">

**Comment by sureshg** [comment]
As mentioned in the doc, you should use [graalvm-ce](https://github.com/graalvm/container#:~:text=RPM%2Dbased1-,graalvm%2Dce,-A%20GraalVM%20Community) image for native image tools.

**Comment by KFCFans** [comment]
Oh, I am following the practice of the official documentation, maybe you need to adjust the official documentation?

![image](https://user-images.githubusercontent.com/9402086/216805518-196f9def-684f-4dd5-8685-7b0894264179.png)

**Comment by KFCFans** [comment]
https://www.graalvm.org/22.0/docs/getting-started/container-images/

**Comment by mlouriz** [comment]
Hi @KFCFans, Please use [graalvm-ce](https://github.com/graalvm/container/pkgs/container/graalvm-ce) it's the gu based images. For jdk, nodejs, and native-image are based on rpm manager ( yum or microdnf). Please feel free to reopen if you are facing any issue.

**Comment by ezzarghili** [comment]
FYI, the type of the image is documented in the readme file of the container repository https://github.com/graalvm/container

**Comment by KFCFans** [comment]
Thank you all~
:)
