### ISSUE TITLE
Update packages

### ISSUE THREAD

**Issue by AlexWayfer** [graalvm/container#80]
The current `latest` package is version 22.3.1

https://github.com/graalvm/container/pkgs/container/truffleruby/65487301?tag=latest

I see already 23.0.1 version: https://github.com/oracle/truffleruby/releases

Can you update packages please? I hope I understand it right.

**Comment by mlouriz** [comment]
Hi @AlexWayfer, FYI we have changed the name of truffleruby image to [truffleruby-community](https://github.com/graalvm/container/tree/master/truffleruby-community) please use the new one.
