### ISSUE TITLE
Unable to run "gu" in graalvm-community images

### ISSUE THREAD

**Issue by UnasZole** [graalvm/container#88]
Hi,

Seeing that the graalvm-ce images are deprecated, I tried to use graalvm-community images instead.
Unfortunately, the "gu" command is not working at all in these images, as demonstrated in the snippet below.

```sh
$ docker run -it --rm ghcr.io/graalvm/graalvm-community:21.0.1-ol9 bash
bash-5.1# gu install wasm
bash: /usr/local/bin/gu: Permission denied
bash-5.1# chmod +x /usr/local/bin/gu
bash-5.1# gu install wasm
/usr/local/bin/gu: line 8: /opt/graalvm-community-java21/bin/gu: No such file or directory
bash-5.1#
```

Two problems : 
- The "gu-wrapper.sh" script, which is copied to /usr/local/bin/gu by the dockerfile, is not executable.
- The gu binary is completely missing from the JAVA_HOME/bin folder

This seems to suggest that one step of this RUN command failed silently during the build, before it reached the chmod : https://github.com/graalvm/container/blob/master/graalvm-community/Dockerfile.ol9-java17#L33-L47

**Comment by oubidar-Abderrahim** [comment]
Hi, Thank you for reaching out about this, Starting from GraalVM for JDK21, `gu` is no longer available.
You can find more about this change among others in our release notes [here](https://www.graalvm.org/release-notes/JDK_21/)

**Comment by UnasZole** [comment]
Thanks, I indeed found that out after opening the ticket.
Nevertheless, in that case it would be useful to update the gu-wrapper.sh to explicitly mention the error that gu is no longer available, and point to the release notes as you did ;-)
